import sys
FIELDS="baseR cc creg cst csta cstb dst dstms dw fstgfcyc h ii mask mode n na offsetR op p ptr r s sc src src1 src2 srcdst srcms sn sz unit t x y z".split()
CODING="ucst scst ucst_minus_one scst_negate ulcst_dpr_byte ulcst_dpr_half ulcst_dpr_word lcst_low16 lcst_high16 pcrel pcrel_half pcrel_half_unsigned reg regpair_lsb regpair_msb areg reg_ptr crlo crhi reg_shift mem_offset mem_offset_noscale mem_mode scaled fstg fcyc spmask reg_unused fu data_fu xpath scst_l3i cst_s3i mem_offset_minus_one mem_offset_minus_one_noscale rside".split()
FORMS="asm_const link_const reg reg_nors reg_bside reg_bside_nors xreg dreg areg b15reg treg zreg retreg regpair xregpair dregpair tregpair irp nrp ilc ctrl mem_short mem_ndw mem_long mem_deref func_unit hw_m1 hw_0 hw_1 hw_5 hw_16 hw_24 hw_31".split()
PIPES="nop 1cycle 1616_m store mul_ext load branch 2cycle_dp 4cycle intdp dpcmp addsubdp mpyi mpyid mpydp mpyspdp mpysp2dp".split()
UNITS="D L M S N".split()
RW="none r w rw".split()
fmts=[];ops=[]
for l in open(sys.argv[1] if len(sys.argv) > 1 else 'raw.txt'):
    t=l.split()
    if not t or t[0].startswith('//'): continue
    if t[0]=='F':
        name,bits,cst,mask,n=t[1],int(t[2]),t[3],t[4],int(t[5])
        fl=[]
        for x in t[6:6+n]:
            fid,rest=x.split(':',1)
            nb,*pieces=rest.split(',')
            ps=[tuple(map(int,p.split('/'))) for p in pieces]
            fl.append((FIELDS[int(fid)],ps))
        fmts.append((name,bits,cst,mask,fl))
    else:
        i=1;name=t[i];i+=1
        unit,fmt,pipe=int(t[i]),int(t[i+1]),int(t[i+2]);i+=3
        isa=int(t[i],16);flags=int(t[i+1],16);i+=2
        nf=int(t[i]);i+=1
        fix=[tuple(map(int,t[i+k].split('/'))) for k in range(nf)];i+=nf
        no=int(t[i]);i+=1
        opi=[tuple(map(int,t[i+k].split('/'))) for k in range(no)];i+=no
        ne=int(t[i]);i+=1
        enc=[tuple(map(int,t[i+k].split('/'))) for k in range(ne)];i+=ne
        ops.append((name,unit,fmt,pipe,isa,flags,fix,opi,enc))
o=sys.stdout
o.write("// C674x instruction formats and opcodes, as data: GENERATED by tools/gen-opcodes - do not edit by hand.\n")
o.write("// The encodings are facts of TI's instruction set (SPRUFE8, appendices C-H); they were collected from the GNU\n")
o.write("// binutils C6X opcode tables and are held, word for word, to TI's own dis6x by oracle/compare.sh.\n\n")
o.write("#ifdef C6X_FORMATS\n")
# binutils reads the compact SPKERNEL's (Uspk) bits 0, 9-7 and 15-14 as bits 0-5 of the fstg/fcyc field; the
# loops cl6x writes fit only with bits 9-7, 15-14 and 0 as bits 0-5 (tests/c6x-uspk.sh, D4).
fmts=[(n,b,c,m,[(fn,[(7,3,0),(14,2,3),(0,1,5)]) if (n=='nfu_uspk' and fn=='fstgfcyc') else (fn,ps) for fn,ps in fl])
      for (n,b,c,m,fl) in fmts]
for (name,bits,cst,mask,fl) in fmts:
    fs=", ".join("{ F_%s, %d, { %s } }"%(fn,len(ps),", ".join("{ %d, %d, %d }"%p for p in ps)) for fn,ps in fl)
    o.write("C6X_FORMAT(%s, %d, %s, %s, %d, { %s })\n"%(name,bits,cst,mask,len(fl),fs))
o.write("#endif\n\n#ifdef C6X_MNEMONICS\n")
seen=[]
for op in ops:
    if op[5]&1: continue
    if op[0].upper() not in seen: seen.append(op[0].upper())
for n in seen: o.write("C6X_MNEMONIC(%s)\n"%n)
o.write("#endif\n\n#ifdef C6X_OPCODES\n")
FL=[(0x1,'MACRO'),(0x4,'MCNOP'),(0x8,'NO_MCNOP'),(0x10,'LOAD'),(0x20,'STORE'),(0x40,'UNALIGNED'),(0x80,'SIDE_B'),(0x100,'SIDE_T2'),(0x200,'NO_CROSS'),(0x400,'CALL'),(0x800,'RETURN'),(0x1000,'SPLOOP'),(0x2000,'SPKERNEL'),(0x4000,'SPMASK'),(0x100000,'SPRED'),(0x200000,'NORS'),(0x400000,'BSIDE'),(0x800000,'B15PTR')]
for (name,unit,fmt,pipe,isa,flags,fix,opi,enc) in ops:
    if flags & 1: continue   # assembler macros: never what a word decodes to
    fl=[n for b,n in FL if flags&b]
    mm=(flags>>16)&0xf
    fs=" | ".join("K_"+n for n in fl) or "0"
    if fmts[fmt][1]==16 and (flags & 0x10 or flags & 0x20): fs += " | KMODE(%d)"%mm
    fx=", ".join("{ F_%s, %d, %d }"%(FIELDS[a],b,c) for a,b,c in fix) or "{ F_none, 0, 0 }"
    op=", ".join("{ O_%s, %d, RW_%s, %d, %d, %d, %d }"%(FORMS[a],b,RW[c],d,e,f,g) for a,b,c,d,e,f,g in opi) or "{ O_none, 0, RW_none, 0, 0, 0, 0 }"
    en=", ".join("{ F_%s, C_%s, %d }"%(FIELDS[a],CODING[b],c) for a,b,c in enc) or "{ F_none, C_none, 0 }"
    o.write('C6X_OPCODE(MN_%s, "%s", U_%s, FMT_%s, P_%s, %s, %d, { %s }, %d, { %s }, %d, { %s })\n'%(name.upper(),name.upper(),UNITS[unit],fmts[fmt][0],PIPES[pipe].replace('1616_m','m1616').replace('1cycle','one').replace('2cycle_dp','dp2').replace('4cycle','four'),fs,len(fix),fx,len(opi),op,len(enc),en))
o.write("#endif\n")
