#!/usr/bin/env python3
"""gen-words.py [packets] [seed] > words.asm

The decoder's oracle corpus: fetch packets of pseudo-random instruction words for TI's dis6x to
disassemble, so that vm6747 --dis-words can be held to dis6x's reading of the same words, word for
word. About a third of the packets carry a compact-instruction header (the eighth word's top nibble
0b1110) with a random layout, expansion and p-bit field, so the 16-bit formats are covered too. The
seed is fixed, so the corpus and its expected disassembly are reproducible.
"""
import random
import sys

packets = int(sys.argv[1]) if len(sys.argv) > 1 else 4096
seed = int(sys.argv[2]) if len(sys.argv) > 2 else 6747
rng = random.Random(seed)

print("; generated by gen-words.py %d %d - do not edit" % (packets, seed))
# .text, not .sect ".text": cl6x 7.4.4 marks only the former SHF_EXECINSTR, and dis6x lists a data section
# as .word - which held the decoder to nothing (review 2026-10-05, 1.6).
print("\t.text")
print("\t.align\t32")
print("\t.global\twords")
print("words:")
for p in range(packets):
    ws = [rng.getrandbits(32) for _ in range(8)]
    if rng.random() < 0.35:
        layout = rng.getrandbits(7)
        expansion = rng.getrandbits(7)
        pbits = rng.getrandbits(14)
        ws[7] = 0xE0000000 | (layout << 21) | (expansion << 14) | pbits
    else:
        # a plain packet: the eighth word is an instruction, so it must not read as a header
        while (ws[7] >> 28) == 0xE:
            ws[7] = rng.getrandbits(32)
    print("\t.word\t" + ",".join("0x%08x" % w for w in ws))
